pool:
  name: Make
  demands:
    - Agent.Name -equals SUPPORT-BUILD-L
  
parameters:
- name: numInstance
  displayName: "Number of Parallel Instances"
  type: number
  default: 1

trigger:
- master

steps:
- task: Bash@3
  displayName: 'Prune Containers'
  inputs:       
    targetType: 'inline'
    script: 'docker container prune -f'

- task: Bash@3
  displayName: 'Remove Existing Images'
  inputs:       
    targetType: 'inline'
    script: 'docker rmi votingportal-cypress -f'

- task: Bash@3
  displayName: 'List Images'
  inputs:       
    targetType: 'inline'
    script: 'docker images'

- task: Bash@3
  displayName: 'List Containers'
  inputs:       
    targetType: 'inline'
    script: 'docker ps -a'

- task: DockerCompose@0
  displayName: 'Run Cypress Tests'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'glasslewis.azurecr.io'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: '--build --scale cypress=${{ parameters.numInstance }}'
