pool:
  name: Make
  demands:
    - Agent.Name -equals SUPPORT-BUILD-L
  
parameters:
- name: numInstance
  displayName: "Number of Parallel Instances"
  type: number
  default: 1

trigger: none

steps:
- task: Bash@3
  displayName: 'Remove Existing Cypress Images'
  inputs:       
    targetType: 'inline'
    script: 'docker rmi glasslewis.azurecr.io/votingportal-cypress votingportal-cypress -f'

- task: DockerCompose@0
  displayName: 'Run Cypress Tests'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'glasslewis.azurecr.io'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: '--build --scale cypress=${{ parameters.numInstance }}'

- task: Bash@3
  displayName: 'Remove Exited Cypress Containers'
  inputs:       
    targetType: 'inline'
    script: 'docker ps --filter name=votingportal-automation-tests* -aq | xargs docker stop | xargs docker rm'