resources:
- repo: self
queue:
  name: Build
  demands: 
  - cypress
trigger:
 branches:
   include:
     - master
schedules:
  - cron: '0 2 * * *'
    displayName: 'Nightly Build at 02:00'
    always: true
    branches:
      include:
        - master

steps:
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'Voting Portal QA'
    method: 'GET'
    headers: |
      {
      }
    waitForCompletion: 'true'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
   
- script: |
    npm install
    export cypress_Internal_Admin_Username=$(InternalAdminUsername)
    export cypress_Internal_Admin_Password=$(InternalAdminPassword)
    npm run cypress:run
  displayName: 'npm install and running cypress'