resources:
- repo: self
queue:
  name: Build
  demands:
  - cypress
  
trigger: 
  branches:
    include:
      - master

schedules:
  - cron: '0 23 * * *'
    displayName: 'Nightly Build at 23:00'
    always: true
    branches:
      include:
        - master

steps:
- script: |
    npm ci
    npm run lint
  displayName: 'npm install and linting'

- script: |
    export cypress_baseUrl=$(BaseUrlTest)
    export cypress_Internal_Admin_Username=$(InternalAdminUsername)
    export cypress_Internal_Admin_Password=$(InternalAdminPassword)
    export HTTP_PROXY=http://10.71.1.42:3128
    npx cypress run --env configFile=qa
  displayName: 'Running cypress'

- task: ArchiveFiles@2
  displayName: 'Archive $(System.DefaultWorkingDirectory)/test-results'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/test-results'
    archiveType: tar
    archiveFile: '$(Build.ArtifactStagingDirectory)/test-results-$(Build.BuildId).tar.gz'
    verbose: true
  condition: failed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Tests Screenshots'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/test-results-$(Build.BuildId).tar.gz'
    ArtifactName: TestResults
  condition: failed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/result-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/test-results/tests-output'
    mergeTestResults: true
    failTaskOnFailedTests: true
  condition: succeededOrFailed()