resources:
- repo: self
queue:
  name: Build
  demands: 
  - cypress
trigger: none
schedules:
  - cron: '0 2 * * *'
    displayName: 'Nightly Build at 02:00'
    always: true
    branches:
      include:
        - master

steps:
- script: |
    npm install
    export cypress_baseUrl=$(BaseUrlTest)
    export cypress_Internal_Admin_Username=$(InternalAdminUsername)
    export cypress_Internal_Admin_Password=$(InternalAdminPassword)
    npm run cypress:run
  displayName: 'npm install and running cypress'