name: '$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)'

parameters:
  - name: testSuite
    displayName: 'Test Suite'
    default: 'Smoke'
    values:
      - 'Smoke'
      - 'Regression'

trigger: none

jobs:
  - job: E2E_Adhoc
    timeoutInMinutes: 75

    steps:
      - script: npm ci
        displayName: 'Install Node Dependencies'

      - script: |
          if [ ${{ parameters.testSuite }} == 'Smoke' ]; then
            tags="--env tags=@Smoke"
          else
            tags="--env tags=@Regression"
          fi
          cypressCommand="npx cypress run --config specPattern=cypress/e2e/**/*.feature $tags"
          echo "Running command: $cypressCommand"
          $cypressCommand
        displayName: 'Run Cypress tests'
