name: '$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)'

parameters:
  - name: testSuite
    displayName: 'Test Suite'
    default: 'Smoke'
    values:
      - 'Smoke'
      - 'Regression'

trigger: none

jobs:
  - job: adhoc_specify_feature_tags
    timeoutInMinutes: 75

    steps:
      - script: npm ci
        displayName: 'Install Node Dependencies'

      - script: |
          if [ ${{ parameters.testSuite }} == 'Smoke' ]; then
            tags="--env tags=@Smoke"
          else
            tags="--env tags=@Regression"
          fi
          cypressCommand="npx cypress run --config specPattern=cypress/e2e/**/*.feature $tags"
          echo "Running command: $cypressCommand"
          $cypressCommand
        displayName: 'Run Cypress tests'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Cucumber Report'
        inputs:
          targetPath: 'test-results/cucumber/cucumber_report.html'
          artifact: 'Report-Run$(System.JobAttempt)-Instance$(System.JobPositionInPhase)'
        continueOnError: true
        condition: succeededOrFailed()

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Failure Screenshots'
        inputs:
          targetPath: 'test-screenshots'
          artifact: 'Screenshots-Run$(System.JobAttempt)-Instance$(System.JobPositionInPhase)'
        continueOnError: true
        condition: failed()
