name: '$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)'

parameters:
  - name: runCommand
    displayName: 'Run Command'
    type: string
    default: 'npx cypress run --config specPattern=cypress/e2e/**/*.feature'

trigger: none

jobs:
  - job: adhoc_specify_full_run_command
    timeoutInMinutes: 75

    steps:
      - script: npm ci
        displayName: 'Install Node Dependencies'

      - script: |
          ${{ parameters.runCommand }}
        displayName: 'Run Cypress tests'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Cucumber Report'
        inputs:
          targetPath: 'test-results/cucumber/cucumber_report.html'
          artifact: 'Report-Run$(System.JobAttempt)-Instance$(System.JobPositionInPhase)'
        continueOnError: true
        condition: succeededOrFailed()

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Failure Screenshots'
        inputs:
          targetPath: 'test-screenshots'
          artifact: 'Screenshots-Run$(System.JobAttempt)-Instance$(System.JobPositionInPhase)'
        continueOnError: true
        condition: failed()
