name: '$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)'

trigger: none

schedules:
  - cron: '0 8 * * 1-5'
    displayName: 'Daily Build at 08:00 GMT'
    always: true
    branches:
      include:
        - master

jobs:
  - job: ViewpointAutomation
    timeoutInMinutes: 75
    pool:
      name: 'VMSS - DEV - QAUAT'
    strategy:
      parallel: 3
    steps:
      - script: |
          npm ci
        displayName: 'Install Node Dependencies'

      - script: |
          export HTTP_PROXY=http://10.71.1.42:3128
          export cypress_url=$(url)
          export cypress_sql_server=$(sql_server)
          export cypress_sql_username=$(sql_username)
          export cypress_sql_password=$(sql_password)
          if [ $(environment) == 'aqua' ]; then
            export cypress_tags="not @sso"
          fi
          npx cypress-cloud run --parallel --record --key xxx --ci-build-id $BUILD_BUILDNUMBER --config specPattern=cypress/e2e/SmokeTests/*.feature
        displayName: 'Run Cypress Tests'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Failure Screenshots'
        inputs:
          targetPath: 'test-screenshots'
          artifact: 'Screenshots-Run$(System.JobAttempt)-Instance$(System.JobPositionInPhase)'
        continueOnError: true
        condition: failed()
