trigger:
  branches:
    include:
      - master

schedules:
  - cron: '0 7 * * 1-5'
    displayName: 'Daily Build at 07:00 GMT'
    always: true
    branches:
      include:
        - master

pool:
  name: 'Build Pipelines VMSS - QAUAT'

jobs:
- job: ViewpointAutomation
  timeoutInMinutes: 90
  steps:
  - script: |
      npm ci
    displayName: 'Install Packages'

  - script: |
      export HTTP_PROXY=http://10.71.1.42:3128
      npx cypress run --reporter junit --config specPattern=cypress/e2e/SmokeTests/*.feature
    displayName: 'Running Cypress Tests'

  - script: |
      node cypress/utils/cucumber-html-reporter.js
    displayName: 'Generate Cucumber Report'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Cucumber Old Report'
    inputs:
      targetPath: 'test-results/cucumber/cucumber_report.html'
      artifact: ReportOld
    continueOnError: true
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Cucumber New Report'
    inputs:
      targetPath: 'test-results/cucumber/cucumber-report.html'
      artifact: ReportNew
    continueOnError: true
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Failure Screenshots'
    inputs:
      targetPath: 'test-results/screenshots'
      artifact: Screenshots
    continueOnError: true
    condition: failed()

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/result-*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/test-results/tests-output'
      mergeTestResults: true
      failTaskOnFailedTests: false
    condition: succeededOrFailed()
