parameters:
  - name: buildParameters
    displayName: 'Build Parameters'
    type: string
    default: 'npx cypress run --config retries=1,specPattern=cypress/e2e/ViewpointTestSuite/**/*.feature'

trigger: none

schedules:
  - cron: '0 20 * * 4'
    displayName: 'Weekly Regression - Every Thu @ 8PM GMT'
    always: true
    branches:
      include:
        - master

pool:
  name: 'Build Pipelines VMSS - QAUAT'

jobs:
- job: ViewpointAutomation
  timeoutInMinutes: 120
  steps:

  - script: |
      npm ci
    displayName: 'Install Packages'

  - script: |
      export HTTP_PROXY=http://10.71.1.42:3128
      export cypress_url=$(url)
      export cypress_sql_server=$(sql_server)
      export cypress_sql_username=$(sql_username)
      export cypress_sql_password=$(sql_password)
      ${{ parameters.buildParameters }}
    displayName: 'Running Cypress Tests'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Cucumber Report'
    inputs:
      targetPath: 'test-results/cucumber/cucumber_report.html'
      artifact: 'Report-$(System.JobAttempt)'
    continueOnError: true
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Failure Screenshots'
    inputs:
      targetPath: 'test-results/screenshots'
      artifact: 'Screenshots-$(System.JobAttempt)'
    continueOnError: true
    condition: failed()

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/result-*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/test-results/tests-output'
      mergeTestResults: true
      failTaskOnFailedTests: false
    condition: succeededOrFailed()
