name: '$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)'

trigger: none

schedules:
  - cron: '30 14 * * 1-5'
    displayName: 'Daily Regression at 15:30 GMT+1'
    always: true
    branches:
      include:
        - master

jobs:
  - job: scheduled-daily-run-of-regression-tag-tests
    timeoutInMinutes: 75
    steps:
      - script: |
          npm ci
        displayName: 'Install Node Dependencies'

      - script: |
          npx cypress run --config specPattern=cypress/e2e/**/*.feature --env tags=@Regression
        displayName: 'Run Cypress Tests'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Cucumber Report'
        inputs:
          targetPath: 'test-results/cucumber/cucumber_report.html'
          artifact: 'Report-Run$(System.JobAttempt)-Instance$(System.JobPositionInPhase)'
        continueOnError: true
        condition: succeededOrFailed()

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Failure Screenshots'
        inputs:
          targetPath: 'test-screenshots'
          artifact: 'Screenshots-Run$(System.JobAttempt)-Instance$(System.JobPositionInPhase)'
        continueOnError: true
        condition: failed()
