parameters:
  - name: buildParameters
    displayName: 'Build Parameters'
    type: string
    default: '--config integrationFolder="cypress/integration/SmokeTests"'

trigger: none

jobs:
- job: ViewpointAutomation
  timeoutInMinutes: 120
  pool: 'Build Pipelines VMSS - QAUAT'
  steps:
  - script: |
      npx cypress cache clear
    displayName: 'Cypress Clear Cache'

  - script: |
      npm ci
    displayName: 'Install Packages'

  - script: |
      export HTTP_PROXY=http://10.71.1.42:3128
      npx cypress run --reporter junit --env configFile=qa ${{ parameters.buildParameters }}
    displayName: 'Running Cypress Tests'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Cucumber Report'
    inputs:
      targetPath: 'test-results/cucumber/cucumber_report.html'
      artifact: Report
    continueOnError: true
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/result-*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/test-results/tests-output'
      mergeTestResults: true
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
