name: Adhoc Full Command

on:
  workflow_dispatch:
    inputs:
      runCommand:
        description: 'Run Command'
        required: true
        default: 'npx cypress run --config specPattern=cypress/e2e/**/*.feature --env tags="not @Ignore"'

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        id: cypress-tests
        run: |
          ${{ inputs.runCommand }}
          echo "Cypress tests completed"
        continue-on-error: true

      - name: Publish Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: Cucumber Report
          path: test-results/cucumber/cucumber_report.html

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'test-screenshots'

      - name: Publish Failure Screenshots
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: Screenshots
          path: test-screenshots
