name: Cypress Tests

on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npx cypress run --config specPattern=cypress/e2e/**/*.feature --env tags=@Regression
        continue-on-error: true

      - name: Generate Report
        run: node cypress/utils/cucumber-html-reporter.js

      - name: Publish Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: test-results/cucumber/cucumber_report.html
